<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // Import DB Facade

class CategoryWiseGradationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('category_wise_gradations')->insert([
            [
                'category' => '1',
                'tournament' => 'Olympics',
                'organising_authority' => 'International Olympic Committee (IOC)',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'A',
            ],
            [
                'category' => '1',
                'tournament' => 'Paralympics',
                'organising_authority' => 'International Paralympics Committee (IPC)',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'A',
            ],
            [
                'category' => '2',
                'tournament' => '4-year World Championship (restricted to Sports disciplines played in Olympics/ Paralympics)',
                'organising_authority' => 'International Federation of concerned game, recognized by IOC/IPC.',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'A',
            ],
            [
                'category' => '3',
                'tournament' => 'Asian Games',
                'organising_authority' => 'Olympic Council of Asia',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'B',
            ],
            [
                'category' => '3',
                'tournament' => 'Para Asian Games',
                'organising_authority' => 'Asian Paralympic Committee',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'B',
            ],
            [
                'category' => '3',
                'tournament' => 'Youth Olympics',
                'organising_authority' => 'IOC',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'B',
            ],
            [
                'category' => '4',
                'tournament' => 'Commonwealth Games',
                'organising_authority' => 'Commonwealth Games Federation',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'B',
            ],
            [
                'category' => '4',
                'tournament' => 'Commonwealth Games (Para Athletes)',
                'organising_authority' => 'Commonwealth Games Federation',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'B',
            ],
            [
                'category' => '4',
                'tournament' => 'Youth Asian Games',
                'organising_authority' => 'Commonwealth Games Federation',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'B',
            ],
            [
                'category' => '5',
                'tournament' => 'Other World/International Championships',
                'organising_authority' => 'International Federation of the concerned game, recognized by the IOC.',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'B',
            ],
            [
                'category' => '5',
                'tournament' => 'Youth Commonwealth Games',
                'organising_authority' => 'Commonwealth Games Federation',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'B',
            ],
            [
                'category' => '5',
                'tournament' => 'Deaflympics',
                'organising_authority' => 'International Committee of Sports for the Deaf (only those recognized by IOC)',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'B',
            ],
            [
                'category' => '5',
                'tournament' => 'Special Olympics',
                'organising_authority' => 'Only those which are recognized by IOC',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'B',
            ],
            [
                'category' => '5',
                'tournament' => 'IPC World Cup/Championship (Held annually or biennially)',
                'organising_authority' => 'IPC',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'B',
            ],
            [
                'category' => '5',
                'tournament' => 'IBSA World Championship',
                'organising_authority' => 'International Blind Sports Federation',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'B',
            ],
            [
                'category' => '6',
                'tournament' => 'World University Games',
                'organising_authority' => 'International University Sports Federation',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'B',
            ],
            [
                'category' => '7',
                'tournament' => 'Other Asian/Commonwealth Championship',
                'organising_authority' => 'Asian Federation of the concerned game, affiliated to the Olympic Council of Asia/International Federation/ Commonwealth Games Federation',
                'medal' => 'Yes',
                'gradation' => 'A',
                'participation' => 'Yes',
                'gradation_participation' => 'B',
            ],
            [
                'category' => '8',
                'tournament' => 'SAF Games',
                'organising_authority' => 'South Asian Games Federation',
                'medal' => 'Yes',
                'gradation' => 'B',
                'participation' => 'Yes',
                'gradation_participation' => 'C',
            ],
            [
                'category' => '9',
                'tournament' => 'International/Domestic Cricket Test/One Day',
                'organising_authority' => 'ICCF/BCCI',
                'medal' => 'Yes',
                'gradation' => 'B',
                'participation' => 'Yes',
                'gradation_participation' => 'C',
            ],
            [
                'category' => '9',
                'tournament' => 'Blind Cricket World Cup',
                'organising_authority' => 'World Blind Cricket Council',
                'medal' => 'Yes',
                'gradation' => null,
                'participation' => 'Yes',
                'gradation_participation' => 'D',
            ],
            [
                'category' => '10',
                'tournament' => 'National Games',
                'organising_authority' => 'Indian Olympic Association',
                'medal' => 'Yes',
                'gradation' => 'C',
                'participation' => 'Yes',
                'gradation_participation' => 'D',
            ],
            [
                'category' => '11',
                'tournament' => 'National Championship',
                'organising_authority' => 'National Federation Affiliated to IOA/Ministry of Sports & Youth Affairs (GOI).',
                'medal' => 'Yes',
                'gradation' => 'C',
                'participation' => 'Yes',
                'gradation_participation' => 'D',
            ],
            [
                'category' => '12',
                'tournament' => 'National School Games/Khelo India/All India Inter University Games/ All India Women Sports/All India Civil Services/All India Police/All India Rural Sports etc.',
                'organising_authority' => 'School Games Federation of India/AIU/Ministry of Sports & Youth Affairs (GOI)',
                'medal' => 'Yes',
                'gradation' => 'D',
                'participation' => 'Yes',
                'gradation_participation' => 'NA',
            ],
            [
                'category' => '13',
                'tournament' => 'State Games/State Women Sports/State School/State Rural & Panchayats/ State Inter-University',
                'organising_authority' => 'Haryana State Association recognized by the concerned National Federation affiliated to IOA/Department of Sports & Youth Affairs (Haryana)',
                'medal' => 'Yes',
                'gradation' => 'D',
                'participation' => 'Yes',
                'gradation_participation' => 'NA',
            ],
        ]);
    }
}
